run_mode :
  mode: debug

app:
  pageSize : 10

server:
  mode: debug
  addr: 8000
  readTimeout: 60
  writeTimeout: 60

database:
  type: mysql
  user: root
  password: xxxx
  host: xx.xx.xx.xx:3306
  name: go

jwt:
  signingKey: xxxxx
  expiresTime: 604800
  bufferTime: 86400

zap:
  level: 'info'
  format: 'console'
  prefix: '[AKA_ZWZ]'
  director: 'log'
  linkName: 'latest_log'
  showLine: true
  encodeLevel: 'LowercaseColorLevelEncoder'
  stacktraceKey: 'stacktrace'
  logInConsole: true
