run_mode :
  mode: debug

app:
  page_size : 10

server:
  addr: 8000
  read_timeout: 60
  write_timeout: 60

database:
  type: mysql
  user: root
  password: xxxxx
  host: xx.xx.xx.xx:3306
  name: go

jwt:
  signing_key: 'dfg6Yf'
  expires_time: 604800
  buffer_time: 86400

zap:
  level: 'info'
  format: 'console'
  prefix: '[AKA_ZWZ]'
  director: 'log'
  link_name: 'latest_log'
  show_line: true
  encode_level: 'LowercaseColorLevelEncoder'
  stacktrace_key: 'stacktrace'
  log_in_console: true
