app:
  pageSize: 10

server:
  mode: debug
  addr: 8000
  readTimeout: 60
  writeTimeout: 60

  aliOSS:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: [ 阿里云accessKeyId ]
    accessKeySecret: [ 阿里云accessKeySecret ]
    bucketName: [ bucket ]
    bucketUrl: [ bucket url ]

database:
  type: mysql
  user: xxx
  password: xxxx
  host: xx.xx.xxx.xx:3306
  name: [ 数据库名 ]

tencent:
  secretId: [ 腾讯云secretId ]
  secretKey: [ 腾讯云secretId ]

redisDB:
  addr: xx.xxx.xx.xx:6379
  password: xxxxx
  db: 0

jwt:
  signingKey: [ jwt signingKey ]
  expiresTime: [ 604800, token过期时长 ]
  bufferTime: [ bufferTime ]

zap:
  level: 'info'
  format: 'console'
  prefix: '[AKA_ZWZ]'
  director: 'log'
  linkName: 'latest_log'
  showLine: true
  encodeLevel: 'LowercaseColorLevelEncoder'
  stacktraceKey: 'stacktrace'
  logInConsole: true
